apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.app_name }}
  namespace: ${{ values.app_name }}
  labels:
    app: ${{ values.app_name }}
    system: ${{ values.system }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - ${{ values.domain_prod }}
    - ${{ values.domain_stage }}
    secretName: ${{ values.app_name }}-tls
  rules:
  - host: ${{ values.domain_prod }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${{ values.app_name }}
            port:
              number: 80
  - host: ${{ values.domain_stage }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${{ values.app_name }}
            port:
              number: 80
