apiVersion: v1
kind: Service
metadata:
  name: ${{ values.app_name }}
  namespace: ${{ values.app_name }}
  labels:
    app: ${{ values.app_name }}
    system: ${{ values.system }}
spec:
  type: ClusterIP
  selector:
    app: ${{ values.app_name }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  sessionAffinity: None
