apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "app.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData: {}
  template:
    metadata:
      name: {{ include "app.fullname" . }}-secrets
      namespace: {{ .Release.Namespace }}
    type: Opaque
