apiVersion: v1
kind: Service
metadata:
  name: ${{ values.app_name }}
spec:
  selector:
    app: ${{ values.app_name }}
  ports:
    - protocol: TCP
      port: ${{ values.service_port }}
      targetPort: ${{ values.service_port }}
