{{- if .Values.reverb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-reverb
  labels:
    {{- include "app.labels" . | nindent 4 }}
    component: reverb
spec:
  replicas: {{ .Values.reverb.replicas }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 4 }}
      component: reverb
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
        component: reverb
    spec:
      containers:
        - name: reverb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: {{ toJson .Values.reverb.command }}
{{- end }}
