{{- range .Values.workers }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" $ }}-worker-{{ .name }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    component: worker-{{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" $ | nindent 6 }}
      component: worker-{{ .name }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" $ | nindent 8 }}
        component: worker-{{ .name }}
    spec:
      containers:
        - name: worker
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          args: {{ toJson .command }}
{{- end }}
{{- end }}
