site_name: '${{ values.app_name }}'
site_description: 'Documentation for ${{ values.app_name }}'

# GitLab repo URL
repo_url: 'https://${{ values.gitlab_host }}/${{ values.ownerPath }}/${{ values.app_name }}'
edit_uri: 'edit/main/docs'

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md'

      