x-app-build: &app-build
  context: .
  dockerfile: Dockerfile
  args:
    COMPOSER_AUTH_JSON: ${COMPOSER_AUTH_JSON}

services:
  # -------------------
  # Laravel App
  # -------------------
  laravel:
    build: *app-build
    container_name: laravel
    volumes:
      - ./src/public:/var/www/html/public
      - ./src/app:/var/www/html/app
      - ./src/bootstrap:/var/www/html/bootstrap
      - ./src/config:/var/www/html/config
      - ./src/database:/var/www/html/database
      - ./src/resources:/var/www/html/resources
      - ./src/routes:/var/www/html/routes
      - ./src/storage:/var/www/html/storage
      - ./src/tests:/var/www/html/tests
      - ./src/vendor:/var/www/html/vendor
      - ./src/.env:/var/www/html/.env
    expose:
      - "9000"
    depends_on: [mariadb, redis]
    networks: [shared-network]

  queue:
    build: *app-build
    container_name: queue
    entrypoint: ["/entrypoint.sh"]
    command: ["php", "artisan", "queue:work", "--tries=3"]
    volumes:
      - ./src/bootstrap:/var/www/html/bootstrap
      - ./src/storage:/var/www/html/storage
      - ./src/vendor:/var/www/html/vendor
      - ./src/.env:/var/www/html/.env
    depends_on: [mariadb, redis]
    networks: [shared-network]

  # -------------------
  # Nginx
  # -------------------
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/local/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [laravel]
    networks: [shared-network]

  # -------------------
  # Redis
  # -------------------
  redis:
    image: redis:alpine
    container_name: redis
    command: >
      /bin/sh -c "redis-server --bind 0.0.0.0 --port 6379 --requirepass password"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks: [shared-network]

  # -------------------
  # MariaDB
  # -------------------
  mariadb:
    image: mariadb:10.6.18
    container_name: mariadb
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks: [shared-network]

volumes:
  redis_data:
  mariadb_data:

networks:
  shared-network:
    driver: bridge
